version: '3.4'

services:
  animaltrackingapp:
    image: ${DOCKER_REGISTRY-}animaltrackingapp
    build:
      context: .
      dockerfile: Dockerfile


# Сервис для разворачивания контейнера с приложением
  webapi:
    build: .
    restart: unless-stopped
    ports:
      - "8080:5000"
    depends_on:
      database:
          condition: service_healthy
    healthcheck:
      test: curl --fail https://localhost:7192/ || exit 1
      interval: 10s
      retries: 5
      timeout: 10s
    


# Сервис для разворачивания контейнера с автотестами
  tests: 
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      webapi:
          condition: service_healthy
    environment:
      SERVER_URL: https://localhost:7192/
      STAGE: 0